# Makefile for supplier-allocation schemas

# Domain-specific settings
DOMAIN = supplier-allocation
PUBLISH_VERSION = 2025-10
ROOT_DIR = $(shell cd ../.. && pwd)

# Include shared makefile rules
include ../common.mk
