# Makefile for cloudevents-example-generator

.PHONY: generate clean

generate:
	npm run generate -- $(ARGS)

generate-default:
	npm run generate -- nhs-notify-example-event.schema.json output/output-example-event.json